config/routes.rb
Rails.application.routes.draw do
  get 'person/index'
  get 'person/show'
  get 'person/edit'
  get 'person/delete'
  
  resources :dramas
  root "dramas#index"
  get 'dramas/new' , "dramas#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dramas
end

app/models/drama.rb
class Drama < ApplicationRecord
  belongs_to :category
  belongs_to :producer, class_name: "Person"
  belongs_to :main_cast, class_name: "Person"
  belongs_to :sub_cast, class_name: "Person"
  belongs_to :set_in_location, class_name: "Location"
  belongs_to :set_in_era, class_name: "Era"

  has_many :dramas_tags
  has_many :tags, through: :dramas_tags
end

app/models/dramas_tag.rb
class DramasTag < ApplicationRecord
  belongs_to :drama
  belongs_to :tag
end

app/models/era.rb
class Era < ApplicationRecord
  has_many :dramas
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :dramas
end

app/models/person.rb
class Person < ApplicationRecord
  has_many_attached :images
  has_many :dramas
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :dramas_tags
  has_many :dramas, through: :dramas_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dramas_controller.rb
class DramasController < ApplicationController
  helper_method :my_tag

  def my_tag(drama_id)
    DramasTag.where(drama_id: drama_id)
  end

  def index
    @dramas = Drama.all
    @people = Person.all
  end

  def show
  end

  def new
    @drama = Drama.new
  end

  def create
    @drama = Drama.new(drama_params)
    respond_to do |format|
      if @drama.save!
        format.html { redirect_to @drama, notice: '登録しました' }
        format.json { render :show, status: :created, location: @drama }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def delete
  end

  private
    def drama_params
      params.require(:drama).permit(:title, :title_orig, :category_id, :releae_date, :producer_id, :main_cast_id, :sub_cast_id, :set_in_location_id, :set_in_era_id )
    end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/dramas/delete.html.slim
h1 Dramas#delete
p Find me in app/views/dramas/delete.html.slim

app/views/dramas/edit.html.slim
h1 Dramas#edit
p Find me in app/views/dramas/edit.html.slim

app/views/dramas/index.html.slim
h1 Dramas#index
最終的にはカードにするのでtagの所は許容する
div.mt-2
  table.table-striped.table-bordered
    thead
      tr
          th title
          th original_title
          th releae_date
          th producer_id
          th main_cast_id
          th sub_cast_id
          th set_in_location_id
          th set_in_era_ids
          th tag
    tbody
      - @dramas.each do |drama|
        tr
          td = drama&.title
          td = drama.title_orig.nil? ? drama&.title : drama&.title_orig
          td = drama&.releae_date
          td = drama&.producer_id
          td = drama&.main_cast_id
          td = drama&.sub_cast_id
          td = drama&.set_in_location_id
          td = drama&.set_in_era_id
          - my_tag(drama.id).each do |drama_tag_table|
              td = drama_tag_table.tag.tag

app/views/dramas/new.html.slim
div.col-12
  = form_for @drama do |f|
      .field
        = f.label :title
        = f.text_field :title, class: "form-control",placeholder: "タイトルを入力して下さい", autofocus: true
      .field
        = f.label :title_orig
        = f.text_field :title_orig, class: "form-control",placeholder: "原題を入力して下さい", autofocus: true
      .field
        =f.label :category_id
        =f.collection_select :category_id, Category.all, :id, :category , { include_blank: "" },  { class: "form-control" }
      .field
        = f.label :releae_date
        = f.date_field :releae_date, value:Date.today.strftime('%Y-%m-%d') ,class: "form-control"
      .field
        =f.label :producer_id
        =f.collection_select :producer_id, Person.all, :id, :name_us , { include_blank: "" },  { class: "form-control" }
      .field
        =f.label :main_cast_id
        =f.collection_select :main_cast_id, Person.all, :id, :name_us , { include_blank: "" },  { class: "form-control" }
      .field
        =f.label :sub_cast_id
        =f.collection_select :sub_cast_id, Person.all, :id, :name_us , { include_blank: "" },  { class: "form-control" }
      .field
        =f.label :set_in_location_id
        =f.collection_select :set_in_location_id, Location.all, :id, :location , { include_blank: "" },  { class: "form-control" }
      .field
        =f.label :set_in_era_id
        =f.collection_select :set_in_era_id, Era.all, :id, :era , { include_blank: "" },  { class: "form-control" }
      .actions = f.submit nil , class: "form-control btn btn-outline-primary mt-2"
      div.my-3
        = link_to '戻る', :back

app/views/dramas/show.html.slim
h1 Dramas#show
p Find me in app/views/dramas/show.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>

  <body class="main-container">
    <%= render "shared/header" %>
    </nav>
    <div class="container"> 
        <div class="row">
           <div class="col-12">
             <%= render "shared/flash" %>
           </div>
        </div>
        <div class="">
            <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/person/delete.html.slim
h1 Person#delete
p Find me in app/views/person/delete.html.slim

app/views/person/edit.html.slim
h1 Person#edit
p Find me in app/views/person/edit.html.slim

app/views/person/index.html.slim
h1 Person#index
p Find me in app/views/person/index.html.slim

app/views/person/show.html.slim
h1 Person#show
p Find me in app/views/person/show.html.slim

app/views/shared/_flash.html.erb
 <% if flash.notice %>
   <div class="alert alert-success" role="alert">
     <%= flash.notice %>
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
 <% end %>
 <% if flash.alert %>
   <div class="alert alert-danger" role="alert">
     <%= flash.alert %>
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
 <% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 sticky-top">
  <%= link_to "TOP", root_path, class: "navbar-brand" %>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Navber">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "NEW", new_drama_path, class: "navbar-brand" %>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ドロップダウン
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">メニュー1</a>
          <a class="dropdown-item" href="#">メニュー2</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">その他</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input type="search" class="form-control mr-sm-2" placeholder="検索..." aria-label="検索...">
      <button type="submit" class="btn btn-outline-success my-2 my-sm-0">検索</button>
    </form>
  </div>
</nav>